name: build Nuget package

on:
  push:
  workflow_dispatch:

env:
  version_suite: 6
  version_major: 6
  version_minor: 0
  version_patch: ${{ format('{0}{1}', github.run_number , github.run_attempt) }}
  tpdm_version: 1.1.0
jobs:  
  ed-fi-repository-scanner:    
    uses: ed-fi-alliance-oss/ed-fi-actions/.github/workflows/repository-scanner.yml@latest
    
  build:
    runs-on: windows-latest
    steps:
      - name: Set env variables 
        run: |
          echo "version_informational=${{ format('v{0}.{1}', env.version_major , env.version_minor ) }}" >> $env:GITHUB_ENV
          echo "version_core=${{ format('{0}.{1}.{2}', env.version_major, env.version_minor , env.version_patch) }}" >> $env:GITHUB_ENV
        #choco install sql-server-2019
        #sc query MSSQLSERVER
        #sqlcmd -S . -E -Q "SELECT @@VERSION;"
          
      - name: Git long filename support
        run: git config --system core.longpaths true
        
      - uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579
        with:
          repository: Ed-Fi-Alliance-OSS/Ed-Fi-ODS
          #ref: ${{ env.version_informational }}
          path: Ed-Fi-ODS

      - uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579
        with:
          repository: Ed-Fi-Alliance-OSS/Ed-Fi-ODS-Implementation
          #ref: ${{ env.version_informational }}
          path: Ed-Fi-ODS-Implementation

      - uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579
        with:
          path: Ed-Fi-Extensions
          
      #- name: Setup DotNet
      #  uses: actions/setup-dotnet@v1
      #  with:
      #    dotnet-version: '3.1.x'
      
      #- uses: NuGet/setup-nuget@v1.0.5
      
      - name: Replace package name
        run: |
          (Get-Content Extensions\EdFi.Ods.Extensions.TPDM\EdFi.Ods.Extensions.TPDM.nuspec) `
          -replace '(?<=<id>)(.*?)(EdFi.Ods.Extensions.TPDM)(?=\b.*</id>)', 'EdFi.Suite${{ env.version_suite }}.Ods.Extensions.TPDM.Community.${{ env.tpdm_version }}' `
          -replace '(?<=<version>)(.*?)(1.0.0)(?=\b.*</version>)','${{ env.tpdm_version }}' |
          Out-File Extensions\EdFi.Ods.Extensions.TPDM\EdFi.Ods.Extensions.TPDM.nuspec
          get-content Extensions\EdFi.Ods.Extensions.TPDM\EdFi.Ods.Extensions.TPDM.nuspec
        working-directory: Ed-Fi-Extensions
      
      - name: Restore NuGet packages
        run: |
          dotnet restore Ed-Fi-ODS/Application/EdFi.Ods.Common/EdFi.Ods.Common.csproj
          dotnet restore Ed-Fi-ODS/Application/EdFi.Ods.Api/EdFi.Ods.Api.csproj
          dotnet restore Ed-Fi-ODS/Application/EdFi.Ods.Standard/EdFi.Ods.Standard.csproj
          dotnet restore Ed-Fi-Extensions/Extensions/EdFi.Ods.Extensions.TPDM/EdFi.Ods.Extensions.TPDM.csproj

      - name: Run CodeGen
        run: |
          (Get-ChildItem -File .).FullName
          $ErrorActionPreference = 'Stop'
          ./Initialize-PowershellForDevelopment.ps1
          initdev -NoRebuild -NoDeploy #Invoke-CodeGen -Engine SQLServer  -ExtensionPaths  ${{ github.workspace }}/Ed-Fi-Extensions/Extensions/EdFi.Ods.Extensions.TPDM
        working-directory: Ed-Fi-ODS-Implementation
        
      - name: Build
        run: dotnet build --configuration release --version-suffix ${{ env.version_core }} --no-restore
        working-directory: ${{ github.workspace }}/Ed-Fi-Extensions/Extensions/EdFi.Ods.Extensions.TPDM

      - name: Pack
        run: | 
          nuget pack EdFi.Ods.Extensions.TPDM.nuspec `
          -OutputDirectory ${{ github.workspace }}\NugetPackages `
          -Version ${{ env.version_core }} `
          -Properties configuration=release `
          -Properties "authors=Ed-Fi Alliance" `
          -Properties "owners=Ed-Fi Alliance" `
          -Properties "copyright=Copyright ©Ed-Fi Alliance, LLC. 2020" `
          -Properties id=EdFi.Suite${{ env.version_suite }}.Ods.Extensions.TPDM.Community.${{ env.tpdm_version }} `
          -Properties title=EdFi.Suite${{ env.version_suite }}.Ods.Extensions.TPDM.Community.${{ env.tpdm_version }} `
          -Properties "description=EdFi.Ods.Extensions.TPDM.Community testing" `
          -NoPackageAnalysis -NoDefaultExcludes
        working-directory: ${{ github.workspace }}/Ed-Fi-Extensions/Extensions/EdFi.Ods.Extensions.TPDM
        
      - name: Upload artifact
        uses: actions/upload-artifact@e448a9b857ee2131e752b06002bf0e093c65e571
        with:
          name: EdFi.Suite3.Ods.Extensions.TPDM.Community.${{ env.tpdm_version }}.${{ env.version_core }}.nupkg
          path: NugetPackages\EdFi.Suite${{ env.version_suite }}.Ods.Extensions.TPDM.Community.${{ env.tpdm_version }}.${{ env.version_core }}.nupkg
