name: Build TPDM extension package

on:
  push:
  workflow_dispatch:
    inputs:
      ODS_version:
        type: string
        required: false
        description: "ODS_version: Ed-Fi ODS/API version. Default: 7.0"
      Ed-Fi-ODS-ref:
        type: string
        required: false
        description: "Ed-Fi-ODS-ref: checks out the specified branch/tag of the Ed-Fi-ODS repo (ignores versions). Default branch if not specified."
      Ed-Fi-ODS-Implementation-ref:
        type: string
        required: false
        description: "Ed-Fi-ODS-Implementation-ref: checks out the specified branch/tag of the Ed-Fi-ODS-Implementation repo (ignores versions). Default branch if not specified."
      Data-Standard-Version:
        type: string
        required: false
        description: "Data-Standard-Version: The version of the Data Standard the extention package will work with. Default: 5.0"

env:
  version_suite: "3"
  ODS_version: "7.0"
  tpdm_version: "1.2.0"
  Data-Standard-Version: "5.0.0"

jobs:
  ed-fi-repository-scanner:
    uses: ed-fi-alliance-oss/ed-fi-actions/.github/workflows/repository-scanner.yml@main

  build:
    runs-on: windows-latest
    steps:
      - name: Set env variables
        run: |
          $version_patch = ${{ format('{0}{1}', github.run_number , github.run_attempt) }}
          if ("${{ github.event.inputs.Ed-Fi-ODS-ref  }}" -ne "") {
            echo "ods_ref=${{ github.event.inputs.Ed-Fi-ODS-ref }}" >> $env:GITHUB_ENV
          }
          if ("${{ github.event.inputs.Ed-Fi-ODS-Implementation-ref  }}" -ne "") {
            echo "ods_ref_implementation=${{ github.event.inputs.Ed-Fi-ODS-Implementation-ref }}" >> $env:GITHUB_ENV
          }
          if ("${{ github.event.inputs.ODS_version  }}" -ne "") {
            echo "ODS_version=${{ github.event.inputs.ODS_version }}" >> $env:GITHUB_ENV
          }
          if ("${{ github.event.inputs.Data-Standard-Version  }}" -ne "") {
            echo "ODS_version=${{ github.event.inputs.Data-Standard-Version }}" >> $env:GITHUB_ENV
          }
          echo ("version_core=${{ env.ODS_version }}." + "$version_patch") >> $env:GITHUB_ENV
      - name: Git long filename support
        run: git config --system core.longpaths true

      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c
        with:
          repository: Ed-Fi-Alliance-OSS/Ed-Fi-ODS
          ref: ${{ env.ods_ref }}
          path: Ed-Fi-ODS

      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c
        with:
          repository: Ed-Fi-Alliance-OSS/Ed-Fi-ODS-Implementation
          ref: ${{ env.ods_ref_implementation }}
          path: Ed-Fi-ODS-Implementation

      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c
        with:
          path: TPDM-Community-Extension

      - name: Download TPDM-Community-Model Artifact
        uses: dawidd6/action-download-artifact@1cf11afe3f1874cee82a8d5a2b45c0fd63f0fa22
        with:
          workflow: build-model.yml
          repo: Ed-Fi-Exchange-OSS/Ed-Fi-TPDM-Community-Model
          path: TPDM-Community-Model

      - name: Move Artifact files to extension
        working-directory: TPDM-Community-Model
        run: |
          cd *
          Move-Item .\Versions\ ${{ github.workspace }}/TPDM-Community-Extension/Extensions/EdFi.Ods.Extensions.TPDM/ -force
      - name: Replace package name
        run: |
          (Get-Content Extensions\EdFi.Ods.Extensions.TPDM\EdFi.Ods.Extensions.TPDM.nuspec) `
          -replace '(<id>).*?(</id>)', '$1EdFi.Suite${{ env.version_suite }}.Ods.Extensions.TPDM.Community.${{ env.tpdm_version }}.Standard.${{ env.Data-Standard-Version }}$2' `
          -replace '(<version>).*?(</version>)','${1}${{ env.version_core }}$2' |
          Out-File Extensions\EdFi.Ods.Extensions.TPDM\EdFi.Ods.Extensions.TPDM.nuspec
          get-content Extensions\EdFi.Ods.Extensions.TPDM\EdFi.Ods.Extensions.TPDM.nuspec
        working-directory: TPDM-Community-Extension

      - name: Restore NuGet packages
        run: |
          dotnet restore Ed-Fi-ODS/Application/EdFi.Ods.Common/EdFi.Ods.Common.csproj
          dotnet restore Ed-Fi-ODS/Application/EdFi.Ods.Api/EdFi.Ods.Api.csproj
          dotnet restore Ed-Fi-ODS/Application/EdFi.Ods.Standard/EdFi.Ods.Standard.csproj
          dotnet restore TPDM-Community-Extension/Extensions/EdFi.Ods.Extensions.TPDM/EdFi.Ods.Extensions.TPDM.csproj
      - name: Run CodeGen
        run: |
          rm -Force ./Plugin/tpdm.ps1
          rm -Recurse -Force ./Plugin/EdFi.Suite3.Ods.Extensions.TPDM.*
          (Get-ChildItem -File .).FullName
          $ErrorActionPreference = 'Stop'
          ./Initialize-PowershellForDevelopment.ps1
          Invoke-CodeGen -Engine SQLServer -extensionVersion ${{env.tpdm_version}} -ExtensionPaths ${{ github.workspace }}/TPDM-Community-Extension/Extensions/EdFi.Ods.Extensions.TPDM
        working-directory: Ed-Fi-ODS-Implementation

      - name: Build
        run: dotnet build --configuration release --version-suffix ${{ env.version_core }} --no-restore
        working-directory: ${{ github.workspace }}/TPDM-Community-Extension/Extensions/EdFi.Ods.Extensions.TPDM

      - name: Pack
        run: |
          nuget pack EdFi.Ods.Extensions.TPDM.nuspec `
          -OutputDirectory ${{ github.workspace }}\NugetPackages `
          -Version ${{ env.version_core }} `
          -Properties "configuration=release" `
          -Properties "id=EdFi.Suite${{ env.version_suite }}.Ods.Extensions.TPDM.Community.${{ env.tpdm_version }}.Standard.${{ env.Data-Standard-Version }}" `
          -Properties "title=EdFi.Suite${{ env.version_suite }}.Ods.Extensions.TPDM.Community.${{ env.tpdm_version }}.Standard.${{ env.Data-Standard-Version }}" `
          -Properties "description=EdFi.Ods.Extensions.TPDM.Community" `
          -NoPackageAnalysis -NoDefaultExcludes
        working-directory: ${{ github.workspace }}/TPDM-Community-Extension/Extensions/EdFi.Ods.Extensions.TPDM

      - name: Upload artifact
        uses: actions/upload-artifact@e448a9b857ee2131e752b06002bf0e093c65e571
        with:
          name: EdFi.Suite3.Ods.Extensions.TPDM.Community.${{ env.tpdm_version }}.Standard.${{ env.Data-Standard-Version }}.nupkg
          path: ${{ github.workspace }}/NugetPackages/*.nupkg
