name: build Nuget package

on:
  release:
    types: [published]
  workflow_dispatch:
  push:

env:
  version_suite: 3
  version_major: 5
  version_minor: 3
  version_patch: ${{ format('{0}{1}', github.run_number , github.run_attempt) }}
  version_informational: $$ {{ format('v{0}.{1}', env.version_major , env.version_minor ) }}
  version_core: $ {{ format('{0}.{1}.{2}', $ {{ env.version_major }}, env.version_minor , env.version_patch) }}

jobs:
  build:
    runs-on: windows-latest
    steps:
      - run: |
          echo "${{ env.version_suite }}"
          echo "${{ env.version_patch }}"
          echo "${{ env.version_core }}"
      - name: Git long filename support
        run: git config --system core.longpaths true
        
      - uses: actions/checkout@v2
        with:
          repository: Ed-Fi-Alliance-OSS/Ed-Fi-ODS
          ref: ${{ env.version.informational }}
          path: Ed-Fi-ODS

      - uses: actions/checkout@v2
        with:
          repository: Ed-Fi-Alliance-OSS/Ed-Fi-ODS-Implementation
          ref: ${{ env.version.informational }}
          path: Ed-Fi-ODS-Implementation

      - uses: actions/checkout@v2
        with:
          path: Ed-Fi-Extensions
          
      - name: Setup DotNet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.x'
      
      - uses: NuGet/setup-nuget@v1.0.5
      
      - name: Replace package name
        run: |
          (Get-Content Extensions\EdFi.Ods.Extensions.TPDM\EdFi.Ods.Extensions.TPDM.nuspec) `
          -replace '"(?<=<id>)(.*?)(EdFi.Ods.Extensions.TPDM)(?=\b.*</id>)"', 'EdFi.Suite${{ env.version.suite }}.Ods.Extensions.TPDM.Community.1.1.0' `
          -replace '"(?<=<version>)(.*?)(1.0.0)(?=\b.*</version>)"','1.1.0' |
          Out-File Extensions\EdFi.Ods.Extensions.TPDM\EdFi.Ods.Extensions.TPDM.nuspec
          get-content Extensions\EdFi.Ods.Extensions.TPDM\EdFi.Ods.Extensions.TPDM.nuspec
        working-directory: Ed-Fi-Extensions
      
      - name: Restore NuGet packages
        run: |
          dotnet restore Ed-Fi-ODS/Application/EdFi.Ods.Common/EdFi.Ods.Common.csproj
          dotnet restore Ed-Fi-ODS/Application/EdFi.Ods.Api/EdFi.Ods.Api.csproj
          dotnet restore Ed-Fi-ODS/Application/EdFi.Ods.Standard/EdFi.Ods.Standard.csproj
          dotnet restore Ed-Fi-Extensions/Extensions/EdFi.Ods.Extensions.TPDM/EdFi.Ods.Extensions.TPDM.csproj

      - name: Run CodeGen
        run: |
          (Get-ChildItem -File .).FullName
          $ErrorActionPreference = 'Stop'
          ./Initialize-PowershellForDevelopment.ps1
          Invoke-CodeGen -Engine SQLServer  -ExtensionPaths  ${{ github.workspace }}/Ed-Fi-Extensions/Extensions/EdFi.Ods.Extensions.TPDM
        shell: pwsh 
        working-directory: Ed-Fi-ODS-Implementation
        
      - name: Build
        run: dotnet build --configuration release --version-suffix ${{ env.version.core }} --no-restore
        working-directory: ${{ github.workspace }}/Ed-Fi-Extensions/Extensions/EdFi.Ods.Extensions.TPDM

      - name: Pack
        run: | 
          nuget pack EdFi.Ods.Extensions.TPDM.nuspec `
          -OutputDirectory ${{ github.workspace }}\NugetPackages `
          -Version ${{ env.version.core }} `
          -Properties configuration=release `
          -Properties "authors=Ed-Fi Alliance" `
          -Properties "owners=Ed-Fi Alliance" `
          -Properties "copyright=Copyright ©Ed-Fi Alliance, LLC. 2020" `
          -Properties id=EdFi.Suite${{ env.version.suite }}.Ods.Extensions.TPDM.Community.1.1.0 `
          -Properties title=EdFi.Suite${{ env.version.suite }}.Ods.Extensions.TPDM.Community.1.1.0 `
          -Properties "description=EdFi.Ods.Extensions.TPDM.Community testing" `
          -NoPackageAnalysis -NoDefaultExcludes
        working-directory: ${{ github.workspace }}/Ed-Fi-Extensions/Extensions/EdFi.Ods.Extensions.TPDM
        
      - name: Upload artifact
        uses: actions/upload-artifact@v2.3.0
        with:
          name: EdFi.Suite3.Ods.Extensions.TPDM.Community.1.1.0.${{ env.version.core }}.nupkg
          path: NugetPackages\EdFi.Ods.Extensions.TPDM.${{ env.version.core }}.nupkg
