name: build Nuget package

on:
  release:
    types: [published]
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Git long filename support
        run: git config --system core.longpaths true
        
      - uses: actions/checkout@v2
        with:
          repository: Ed-Fi-Alliance-OSS/Ed-Fi-ODS
          path: Ed-Fi-ODS

      - uses: actions/checkout@v2
        with:
          repository: Ed-Fi-AlliCance-OSS/Ed-Fi-ODS-Implementation
          path: Ed-Fi-ODS-Implementation

      - uses: actions/checkout@v2
        with:
          path: Ed-Fi-Extensions
          
      - name: Setup DotNet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.x'
      
      - uses: NuGet/setup-nuget@v1.0.5
      
      - name: Restore NuGet packages
        run: |
          dotnet restore Ed-Fi-ODS/Application/EdFi.Ods.Common/EdFi.Ods.Common.csproj
          dotnet restore Ed-Fi-ODS/Application/EdFi.Ods.Api/EdFi.Ods.Api.csproj
          dotnet restore Ed-Fi-ODS/Application/EdFi.Ods.Standard/EdFi.Ods.Standard.csproj
          dotnet restore Ed-Fi-Extensions/Extensions/EdFi.Ods.Extensions.TPDM/EdFi.Ods.Extensions.TPDM.csproj

      - name: Run CodeGen
        run: |
          (Get-ChildItem -File .).FullName
          $ErrorActionPreference = 'Stop'
          ./Initialize-PowershellForDevelopment.ps1
          Invoke-CodeGen -Engine SQLServer  -ExtensionPaths  ${{ github.workspace }}/Ed-Fi-Extensions/Extensions/EdFi.Ods.Extensions.TPDM
        shell: pwsh 
        working-directory: Ed-Fi-ODS-Implementation
