name: build Nuget package

on:
  release:
    types: [published]
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: Ed-Fi-Alliance-OSS/Ed-Fi-ODS
          path: Ed-Fi-ODS

      - uses: actions/checkout@v2
        with:
          repository: Ed-Fi-Alliance-OSS/Ed-Fi-ODS-Implementation
          path: Ed-Fi-ODS-Implementation

      - uses: actions/checkout@v2
        with:
          path: Ed-Fi-Extensions
    
      - uses: NuGet/setup-nuget@v1.0.5

      - name: Setup DotNet
        with:
          dotnet-version: '3.1.x'
      
      - run: dotnet restore 
