name: Publish to Azure Artifacts

on:
  workflow_dispatch:
  push:

jobs:
  publish:
    runs-on: windows-latest

    steps:
      - name: Download Nuget package
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: build-nuget-package.yml
